title: Simon Ming
description: Food Experts
site_title: 'Simon Ming'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
# github_username: abhn
blog_url: https://www.nagekar.com
email: crispylemonshrimp@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
# google_analytics: 